name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
# TODO: add testing steps here
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ Secrets.GH_TOKEN }}
          release_branches: main,release/*,hotfix/*
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ Secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
#TODO: consider dockerhub push action (if we decide don't like DH pull)
